version: '3'

tasks:
  run:
    cmds:
      - task install
      
  install:
    cmds:
      - sh ./scripts/taskfile.install.sh
      
  build-prod:
    cmds:
      - go build -v -i -ldflags "-X main.Environment=production" main.go
      
  clean:
    cmds:
      - sh ./scripts/taskfile.clean.sh
      
  fmt:
    cmds:
    - sh ./scripts/taskfile.fmt.sh

  lint:
    cmds:
    - sh ./scripts/taskfile.lint.sh

  test:
    cmds:
      - sh ./scripts/taskfile.test.sh
      
  database:
    cmds:
      - sh ./scripts/taskfile.database.sh 

  dev:
    cmds:
      - sh ./scripts/taskfile.dev.sh
  prod:
    cmds:
      - sh ./scripts/taskfile.prod.sh

  coverage:
    cmds:
      - sh ./scripts/taskfile.coverage.sh
      
  js:
    cmds:
      - sh ./scripts/taskfile.js.sh
