name: golangci-lint
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Run only on tags'     
        required: true
        default: 'true'
#   pull_request:
#     branches:
#       - main

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install requirements
        run: |
          go install github.com/charmbracelet/gum@latest
          go mod download
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.58.1
          go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
      - name: Lint
        run: |
          golangci-lint run
      - name: Vet
        run: |
          sqlc vet
          go vet ./...
      - name: Run Revive Action by pulling pre-built image
        uses: docker://morphy/revive-action:v2
        with:
            config: .revive.toml
